# Generated by Django 4.2 on 2023-04-07 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['id', 0]},
        ),
    ]
