# Generated by Django 4.2 on 2023-04-07 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_wishlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={},
        ),
    ]
