# Generated by Django 4.2 on 2023-04-07 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_wishlist_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='qr_code',
            new_name='qr_code_text',
        ),
    ]
