# Generated by Django 4.2 on 2023-04-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_qr_code_wishlist_qr_code_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='client_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
