# Generated by Django 4.2 on 2023-04-08 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_wishlist_client_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='client_token',
            new_name='client_id',
        ),
    ]
