# Generated by Django 4.2 on 2023-04-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_wishlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
