# Generated by Django 4.2 on 2023-04-14 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availability',
            new_name='available',
        ),
    ]
