# Generated by Django 4.2 on 2023-04-22 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
