# Generated by Django 4.2 on 2023-05-01 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_rename_image1_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail3',
        ),
    ]
