# Generated by Django 4.2 on 2023-05-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_remove_product_thumbnail_remove_product_thumbnail2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
