# Generated by Django 4.2 on 2023-05-10 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_remove_product_categories_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='fee',
        ),
    ]
