# Generated by Django 4.2 on 2023-05-10 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_rename_price_product_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='smallPiece',
            new_name='smallPieces',
        ),
    ]
