# Generated by Django 4.2 on 2023-05-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_rename_smallpiece_product_smallpieces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
