# Generated by Django 4.2 on 2023-05-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_product_inventarnummer_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventarnummer',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
