# Generated by Django 4.2 on 2023-05-11 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_product_image2_product_image3_product_image4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
    ]
