# Generated by Django 4.2 on 2023-05-13 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_alter_product_options_alter_product_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',)},
        ),
    ]
